version: "3.8"

services:
  api:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile.api
    container_name: backend
    environment:
      - ARTIFACTS_DIR=/app/artifacts
      - FEATURES_TRANSFORM_NAME=preprocessing_pipeline
      - TARGET_TRANSFORM_NAME=target_transform
      - PREDICTOR_NAME=regression_model
      - PROPERTY_TYPES_NAME=property_types
      - NEIGHBORHOOD_NAME=neighborhoods
    volumes:
      - ./backend/artifacts:/app/artifacts
    networks:
      - housepriceprediction-network
    ports:
      - 8000:8000

  frontend:
    image: frontend
    build: 
      context: frontend
      dockerfile: ./Dockerfile.app
    container_name: frontend
    environment:
      - VITE_API_URL=http://127.0.0.1:8000/api/
    depends_on:
      - api
    networks:
      - housepriceprediction-network
    ports:
      - 80:80

networks:
  housepriceprediction-network:
    name: housepriceprediction-network
